module.exports = {
  DOCTOR_APPROVED: "DOCTOR_APPROVED",
  DOCTOR_REJECTED: "DOCTOR_REJECTED",

  APPOINTMENT_REQUESTED: "APPOINTMENT_REQUESTED",
  APPOINTMENT_CONFIRMED: "APPOINTMENT_CONFIRMED",
  APPOINTMENT_REJECTED: "APPOINTMENT_REJECTED",
  APPOINTMENT_CANCELLED_BY_PATIENT: "APPOINTMENT_CANCELLED_BY_PATIENT",
  APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",
  APPOINTMENT_REMINDER: "APPOINTMENT_REMINDER",
};
